### ISSUE TITLE
Documentation URL's Don't Work

### ISSUE THREAD

**Issue by yannduran** [nkdAgility/vsts-git-tasks#1]
*Full documentation is available on* http://vsts-git-sync.readthedocs.io 

but it shows:

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

Also *Learn more about this extension on the wiki!*, but cllicking on the wiki just returns to the repo main page.

**Comment by MrHinsh** [comment]
See: http://vsts-git-tasks.readthedocs.io

**Comment by yannduran** [comment]
Thanks Martin, that link works. I was alerting you to the fact that the documentation link on the marketplace page is incorrect and needs fixing or changing (see section below).

>Steps
>
>After installing the extension, you can add one (or more) of the tasks to a new or existing build definition or release definition
>
>Full documentation is available on http://vsts-git-**sync**.readthedocs.io

**Comment by MrHinsh** [comment]
This should now be fixed.. can you check?

**Comment by yannduran** [comment]
Yes Martin, it's working fine now. Thanks again
